-- IMPORTANT NOTES:
--
-- > The database name must be DOCBASE.
-- > You must not change any of the attributes in the tables.
--
-- DATABASE NAME: DOCBASE
--
-- Create user to access:
-- GRANT ALL PRIVILEGES ON DOCBASE.* TO 'docbase'@'%' IDENTIFIED BY 'docbase' WITH GRANT OPTION;
--
--
-- CREATE DATABASE DOCBASE
--
--

CREATE TABLE `DOCSECURITY` (
  `ID` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `OPERADOR` varchar(15) DEFAULT NULL,
  `SENHA` blob,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `OPERADOR` (`OPERADOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='QDOCLIB::OPERATORS REG';

-- IMPORTANT: It's necessary to add a record in the DOCSECURITY table
-- with the username 'admin' and password 'admin'.
INSERT INTO DOCSECURITY (OPERADOR, SENHA) VALUES ('admin', DES_ENCRYPT('admin','admin'));

CREATE TABLE `DOCDEPARTAMENTOS` (
  `DP_IDENT` int(11) NOT NULL AUTO_INCREMENT,
  `DP_NOME` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`DP_IDENT`),
  UNIQUE KEY `DP_NOME` (`DP_NOME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='QDOCBASE::DEPARTMENTS';

-- IMPORTANT: You must add the first record in the DOCDEPARTAMENTOS
-- table, as follows:
INSERT INTO DOCDEPARTAMENTOS (DP_NOME) VALUES ('IT');

CREATE TABLE `DOCENTITY` (
  `ET_IDENT` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `ET_DATA` date NOT NULL,
  `ET_ATIVO` tinyint(4) NOT NULL DEFAULT '1',
  `ET_CATEG` tinyint(4) NOT NULL DEFAULT '0',
  `ET_NOME` varchar(60) NOT NULL,
  `ET_ALIAS` varchar(30) DEFAULT NULL,
  `ET_ENDER` varchar(60) NOT NULL,
  `ET_BAIR` varchar(60) NOT NULL,
  `ET_CITY` varchar(60) NOT NULL,
  `ET_UF` char(2) DEFAULT NULL,
  `ET_CEP` char(10) DEFAULT NULL,
  `ET_TELMOD1` varchar(25) DEFAULT NULL,
  `ET_TELNUM1` varchar(30) DEFAULT NULL,
  `ET_TELMOD2` varchar(25) DEFAULT NULL,
  `ET_TELNUM2` varchar(30) DEFAULT NULL,
  `ET_TELMOD3` varchar(25) DEFAULT NULL,
  `ET_TELNUM3` varchar(30) DEFAULT NULL,
  `ET_TELMOD4` varchar(25) DEFAULT NULL,
  `ET_TELNUM4` varchar(30) DEFAULT NULL,
  `ET_CONTATO1` varchar(40) DEFAULT NULL,
  `ET_EMAIL1` varchar(255) DEFAULT NULL,
  `ET_CONTATO2` varchar(40) DEFAULT NULL,
  `ET_EMAIL2` varchar(255) DEFAULT NULL,
  `ET_CPF` varchar(19) DEFAULT NULL,
  `ET_RG` varchar(21) DEFAULT NULL,
  `ET_CNPJ` varchar(19) DEFAULT NULL,
  `ET_IE` varchar(20) DEFAULT NULL,
  `ET_IM` varchar(20) DEFAULT NULL,
  `ET_URL` varchar(255) DEFAULT NULL,
  `ET_OBCOD` smallint(6) DEFAULT NULL,
  `ET_OBANO` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ET_OBCLI` bigint(20) unsigned NOT NULL DEFAULT '0',
  `ET_OBCEI` varchar(20) DEFAULT NULL,
  `ET_OBCRONO` smallint(6) NOT NULL DEFAULT '0',
  `ET_OUTESPEC` varchar(50) DEFAULT NULL,
  `ET_OUTNFLD1` varchar(15) DEFAULT NULL,
  `ET_OUTDFLD1` varchar(255) DEFAULT NULL,
  `ET_OUTNFLD2` varchar(15) DEFAULT NULL,
  `ET_OUTDFLD2` varchar(255) DEFAULT NULL,
  `ET_OUTOBS` varchar(255) DEFAULT NULL,
  `ET_OBSGER` text,
  PRIMARY KEY (`ET_IDENT`),
  KEY `ET_DATA` (`ET_DATA`),
  KEY `ET_ATIVO` (`ET_ATIVO`),
  KEY `ET_CATEG` (`ET_CATEG`),
  KEY `ET_NOME` (`ET_NOME`),
  KEY `ET_ALIAS` (`ET_ALIAS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='QDOCLIB2::UNIFIED ENTITIES';

CREATE TABLE `DOCIMAGES` (
  `IM_IDENT` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `DL_IDENT` bigint(20) unsigned NOT NULL,
  `IM_IMAGE` longblob,
  PRIMARY KEY (`IM_IDENT`),
  KEY `DL_IDENT` (`DL_IDENT`),
  CONSTRAINT `DOCIMAGES_ibfk_1` FOREIGN KEY (`DL_IDENT`) REFERENCES `DOCLIBRARY` (`DL_IDENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='QDOCLIB2::SCANNED IMGS';

CREATE TABLE `DOCLIBRARY` (
  `DL_IDENT` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `DL_DTCADAST` date NOT NULL,
  `DL_TIPO` tinyint(4) NOT NULL DEFAULT '0',
  `DL_OPERADOR` varchar(15) NOT NULL,
  `ET_IDENT` bigint(20) unsigned NOT NULL,
  `DL_ETRELA` bigint(20) unsigned NOT NULL,
  `DL_DTDOC` date NOT NULL DEFAULT '0000-00-00',
  `DL_NUMERO` int(10) unsigned NOT NULL DEFAULT '0',
  `DL_VALOR` decimal(12,2) NOT NULL DEFAULT '0.00',
  `DL_DPTO` varchar(15) DEFAULT NULL,
  `DL_ARQUIVO` varchar(255) DEFAULT NULL,
  `DL_ARQTIPO` tinyint(4) NOT NULL DEFAULT '0',
  `DL_OBS` text NOT NULL,
  `DL_FNAME` varchar(254) DEFAULT NULL,
  `DL_TOPSEC` tinyint(4) NOT NULL DEFAULT '0',
  `DL_FIELD01DATA` varchar(255) DEFAULT NULL,
  `DL_FIELD02DATA` varchar(255) DEFAULT NULL,
  `DL_FIELD03DATA` varchar(255) DEFAULT NULL,
  `DL_FIELD04DATA` varchar(255) DEFAULT NULL,
  `DL_FIELD05DATA` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`DL_IDENT`),
  KEY `DL_TIPO` (`DL_TIPO`),
  KEY `DL_NUMERO` (`DL_NUMERO`),
  KEY `ET_IDENT` (`ET_IDENT`),
  KEY `DL_ETRELA` (`DL_ETRELA`),
  CONSTRAINT `DOCLIBRARY_ibfk_1` FOREIGN KEY (`ET_IDENT`) REFERENCES `DOCENTITY` (`ET_IDENT`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='QDOCLIB::DOCUMENTS LIB';

CREATE TABLE `DOCSYSACTIVITY` (
  `ACT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACT_HOSTNAME` varchar(255) DEFAULT NULL,
  `ACT_USER` varchar(30) DEFAULT NULL,
  `ACT_MODULE` smallint(6) DEFAULT '-1',
  `ACT_OPERATION` tinyint(4) DEFAULT '-1',
  `ACT_DOCID` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`ACT_ID`),
  KEY `ACT_TIMESTAMP` (`ACT_TIMESTAMP`),
  KEY `ACT_USER` (`ACT_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DOCBASE::LOG SYSTEM';
